"""empty message

Revision ID: 15abf17530ce
Revises: cfe66af09949
Create Date: 2025-11-25 09:12:27.392434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15abf17530ce'
down_revision: Union[str, Sequence[str], None] = 'cfe66af09949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # CONTACTS
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE contacts SET user_id = owner_id")
    op.alter_column('contacts', 'user_id', nullable=False)
    op.drop_constraint(op.f('contacts_owner_id_fkey'), 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'owner_id')
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # DEALS
    op.add_column('deals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE deals SET user_id = owner_id")
    op.alter_column('deals', 'user_id', nullable=False)
    op.drop_constraint(op.f('deals_owner_id_fkey'), 'deals', type_='foreignkey')
    op.drop_constraint(op.f('deals_contact_id_fkey'), 'deals', type_='foreignkey')
    op.drop_column('deals', 'owner_id')
    op.drop_column('deals', 'contact_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('deals', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key(op.f('deals_contact_id_fkey'), 'deals', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('deals_owner_id_fkey'), 'deals', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.alter_column('deals', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('deals', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('deals', 'user_id')
    op.add_column('contacts', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key(op.f('contacts_owner_id_fkey'), 'contacts', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('contacts', 'user_id')
    # ### end Alembic commands ###
