"""empty message

Revision ID: d6e2c601b01a
Revises: 15abf17530ce
Create Date: 2025-11-26 09:48:08.878513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6e2c601b01a'
down_revision: Union[str, Sequence[str], None] = '15abf17530ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE typeactivity AS ENUM "
        "('COMMENT', 'STATUS_CHANGED', 'TASK_CREATED', 'SYSTEM')"
    )
    op.alter_column(
        'activities',
        'type',
        type_=sa.Enum(
            'COMMENT',
            'STATUS_CHANGED',
            'TASK_CREATED',
            'SYSTEM',
            name='typeactivity'
        ),
        postgresql_using="type::typeactivity",
        existing_type=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column('deals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('deals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'deals', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.alter_column('deals', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('deals', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column(
        'activities',
        'type',
        type_=sa.VARCHAR(length=50),
        postgresql_using="type::text",
        existing_type=sa.Enum(
            'COMMENT',
            'STATUS_CHANGED',
            'TASK_CREATED',
            'SYSTEM',
            name='typeactivity'
        ),
        existing_nullable=False,
    )

    op.execute("DROP TYPE typeactivity")
    # ### end Alembic commands ###
